version: "2"
run:
  build-tags:
    - netgo
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: UK
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - gosec
          - revive
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
